---


- name: Insert Filebeat prespector to configuration.
  template:
    src: prospector.yml.j2
    dest: "{{ filebeat_config_dir }}/conf.d/{{ filebeat_prospectors_name }}.yml"
  notify: restart filebeat
  become: yes

